#!/bin/bash

echo "🚀 Quick Start for Lead Tracker React"
echo ""
echo "Since npm install is taking a while, let's get you started!"
echo ""
echo "1. You need to add your Google Apps Script URL to .env.local"
echo "   Edit: .env.local"
echo "   Add: NEXT_PUBLIC_GOOGLE_SCRIPT_URL=your-url-here"
echo ""
echo "2. If you have an OpenAI API key, add it too:"
echo "   Add: OPENAI_API_KEY=sk-your-key-here"
echo ""
echo "3. Run the development server:"
echo "   npm run dev"
echo ""
echo "The app will be available at: http://localhost:3000"
echo ""
echo "Note: If npm install is still running, wait for it to complete."
echo "You can check progress with: ls node_modules | wc -l"
echo "(Should show ~300+ directories when complete)"