export interface BusinessCategory {
  tier: string;
  category: string;
  description: string;
  businesses: string[];
  acquisitionScore: number; // 1-10, higher is better
}

export const GREY_TSUNAMI_CATEGORIES: BusinessCategory[] = [
  {
    tier: "TIER 1",
    category: "Essential Home Services",
    description: "Most actively acquired by PE, recession-resistant",
    acquisitionScore: 10,
    businesses: [
      "HVAC Services",
      "Plumbing Services",
      "Electrical Services",
      "Roofing & Siding",
      "Pest Control",
      "Landscaping/Lawn Care",
      "Tree Service",
      "Irrigation Systems",
      "Gutter Installation & Cleaning",
      "Chimney Cleaning & Repair",
      "Foundation Repair",
      "Waterproofing Services",
      "Septic Tank Services",
      "Well Drilling & Pump Services",
      "Garage Door Installation/Repair",
      "Insulation Services",
      "Mold Remediation",
      "Fire & Water Damage Restoration",
      "Radon Mitigation",
      "Home Energy Audits",
      "Crawl Space Encapsulation",
      "Sewer Line Repair",
      "Drain Cleaning Services",
      "Emergency Plumbing Services",
      "Backflow Testing & Prevention",
      "Gas Line Installation/Repair",
      "Generator Installation & Service",
      "Solar Panel Installation",
      "Home Security Installation",
      "Central Vacuum Systems",
      "Water Softener Installation",
      "Air Quality Services",
      "Duct Cleaning Services",
      "Attic Ventilation",
      "Wildlife Removal Services",
      "Termite Treatment",
      "Mosquito Control Services",
      "Rodent Control Services",
      "Bed Bug Treatment",
      "Bird Control Services",
      "Boiler Services",
      "Radiant Heat Installation",
      "Hydronic Heating Services",
      "Oil Tank Removal",
      "Underground Tank Services",
      "Furnace Repair & Installation",
      "Heat Pump Services",
      "Geothermal HVAC",
      "Commercial Refrigeration",
      "Walk-In Cooler Repair",
      "Ice Machine Services"
    ]
  },
  {
    tier: "TIER 2",
    category: "Property & Facility Services",
    description: "Steady contracts, recurring revenue",
    acquisitionScore: 9,
    businesses: [
      "Property Management Companies",
      "Commercial Cleaning Services",
      "Janitorial Services",
      "Parking Lot Striping/Maintenance",
      "Snow Removal Services",
      "Window Cleaning (Commercial/Residential)",
      "Pressure Washing Services",
      "Building Maintenance",
      "HOA Management",
      "Apartment Complex Management",
      "Facility Management Services",
      "Carpet Cleaning Services",
      "Floor Waxing & Stripping",
      "Post-Construction Cleanup",
      "Medical Facility Cleaning",
      "School Cleaning Services",
      "Church Cleaning Services",
      "Office Cleaning Services",
      "Retail Store Cleaning",
      "Restaurant Cleaning Services",
      "Move-In/Move-Out Cleaning",
      "Vacation Rental Cleaning",
      "Airbnb Cleaning Services",
      "Crime Scene Cleanup",
      "Hoarding Cleanup",
      "Biohazard Cleanup",
      "Parking Garage Cleaning",
      "Stadium/Arena Cleaning",
      "Industrial Cleaning Services",
      "Warehouse Cleaning",
      "Construction Site Services",
      "Portable Toilet Rental",
      "Dumpster Rental Services",
      "Parking Lot Sweeping",
      "Street Sweeping Services",
      "Graffiti Removal",
      "Ice Dam Removal",
      "Holiday Decoration Services",
      "Shopping Center Management",
      "Storage Facility Management",
      "Marina Management",
      "Mobile Home Park Management",
      "RV Park Management",
      "Trailer Park Management",
      "Condo Association Management",
      "Co-op Management",
      "Timeshare Management",
      "Student Housing Management",
      "Senior Living Management",
      "Affordable Housing Management"
    ]
  },
  {
    tier: "TIER 3",
    category: "Home Improvement & Remodeling",
    description: "High-ticket services, established customer base",
    acquisitionScore: 9,
    businesses: [
      "Kitchen Remodeling",
      "Bathroom Remodeling",
      "Basement Finishing",
      "Room Additions",
      "Whole House Remodeling",
      "Sunroom Installation",
      "Deck Building & Repair",
      "Patio Construction",
      "Pergola & Gazebo Installation",
      "Fence Installation & Repair",
      "Driveway Paving/Sealing",
      "Concrete Services",
      "Masonry & Brickwork",
      "Stucco Application",
      "Window Replacement",
      "Door Installation",
      "Siding Installation",
      "Skylight Installation",
      "Crown Molding Installation",
      "Flooring Installation",
      "Hardwood Floor Refinishing",
      "Tile Installation",
      "Carpet Installation",
      "Epoxy Floor Coating",
      "Cabinet Refacing",
      "Countertop Installation",
      "Closet Organization Systems",
      "Home Theater Installation",
      "Wine Cellar Construction",
      "Sauna/Steam Room Installation",
      "Accessibility Modifications",
      "Aging-in-Place Remodeling",
      "Historic Home Restoration",
      "Green Home Retrofitting"
    ]
  },
  {
    tier: "TIER 4",
    category: "Automotive & Transportation",
    description: "Essential services, aging owner demographics",
    acquisitionScore: 8,
    businesses: [
      "Auto Repair Shops",
      "Transmission Repair",
      "Auto Body Shops",
      "Tire Shops",
      "Oil Change/Quick Lube",
      "Car Washes",
      "Auto Detailing",
      "Towing Services",
      "Mobile Mechanic Services",
      "Fleet Maintenance",
      "Diesel Repair",
      "RV Repair Services",
      "Motorcycle Repair",
      "Auto Glass Repair",
      "Muffler & Exhaust Repair",
      "Brake Repair Specialists",
      "Auto A/C Repair",
      "Auto Upholstery",
      "Auto Electric Repair",
      "Classic Car Restoration",
      "Performance Tuning",
      "Boat Repair Services",
      "Marine Services",
      "Small Engine Repair",
      "ATV/UTV Repair",
      "Truck Accessories",
      "Auto Parts Store",
      "Used Auto Parts/Salvage",
      "Mobile Oil Change",
      "Paintless Dent Repair",
      "Window Tinting",
      "Vehicle Wraps",
      "Roadside Assistance"
    ]
  },
  {
    tier: "TIER 5",
    category: "Healthcare & Professional Practices",
    description: "High value, requires licensed buyers",
    acquisitionScore: 7,
    businesses: [
      "Dental Practices",
      "Veterinary Clinics",
      "Optometry Practices",
      "Physical Therapy Clinics",
      "Chiropractic Offices",
      "Home Healthcare Agencies",
      "Medical Equipment Supply",
      "Pharmacy (Independent)",
      "Hearing Aid Centers",
      "Podiatry Practices",
      "Speech Therapy Clinics",
      "Occupational Therapy",
      "Medical Billing Services",
      "Dental Labs"
    ]
  },
  {
    tier: "TIER 6",
    category: "B2B Professional Services",
    description: "Stable client base, recurring revenue",
    acquisitionScore: 8,
    businesses: [
      "Accounting Firms",
      "Bookkeeping Services",
      "Insurance Agencies",
      "Payroll Services",
      "Staffing Agencies",
      "Commercial Print Shops",
      "Sign Shops",
      "IT Services/MSP",
      "Business Consulting",
      "HR Consulting",
      "Marketing Agencies",
      "Commercial Real Estate",
      "Freight Brokerage",
      "Document Shredding Services",
      "Customs Brokerage",
      "Import/Export Services",
      "Logistics Consulting",
      "Supply Chain Consulting",
      "Energy Consulting",
      "Environmental Consulting",
      "Safety Consulting",
      "Quality Control Services",
      "Regulatory Compliance",
      "Grant Writing Services",
      "Bid Writing Services",
      "Technical Writing Services",
      "Translation Services",
      "Court Reporting Services",
      "Process Serving",
      "Private Investigation",
      "Background Check Services",
      "Drug Testing Services",
      "Employee Screening Services"
    ]
  },
  {
    tier: "TIER 7",
    category: "Boring But Profitable",
    description: "Low maintenance, steady cash flow",
    acquisitionScore: 9,
    businesses: [
      "Laundromats",
      "Self-Storage Facilities",
      "Car Washes (Automatic)",
      "Vending Machine Routes",
      "ATM Routes",
      "Parking Lots/Garages",
      "Mobile Home Parks",
      "RV Parks/Campgrounds",
      "Coin-Op Laundry",
      "Ice Vending Machines",
      "Billboard Rental",
      "Equipment Rental",
      "Party/Event Rental",
      "Tool Rental"
    ]
  },
  {
    tier: "TIER 8",
    category: "Specialty Retail & Services",
    description: "Local monopolies, established customer base",
    acquisitionScore: 7,
    businesses: [
      "Liquor Stores",
      "Convenience Stores",
      "Dry Cleaners",
      "Florists",
      "Trophy/Awards Shops",
      "Uniform/Embroidery Services",
      "Locksmith Services",
      "Shoe Repair",
      "Alterations/Tailoring",
      "Pet Grooming",
      "Pack & Ship Stores",
      "Pawn Shops",
      "Check Cashing Services",
      "Jewelry Repair"
    ]
  },
  {
    tier: "TIER 9",
    category: "Manufacturing & Industrial",
    description: "Specialized equipment, trained workforce",
    acquisitionScore: 7,
    businesses: [
      "Machine Shops",
      "Metal Fabrication",
      "Powder Coating",
      "Small Parts Manufacturing",
      "Industrial Equipment Repair",
      "Welding Services",
      "Tool & Die Shops",
      "Plastic Injection Molding",
      "CNC Machining",
      "Sheet Metal Fabrication",
      "Industrial Painting",
      "Sandblasting Services",
      "Heat Treating Services",
      "Precision Grinding",
      "Electroplating Services",
      "Anodizing Services",
      "Vacuum Forming",
      "Rotational Molding",
      "Compression Molding",
      "Die Cutting Services",
      "Laser Cutting Services",
      "Water Jet Cutting",
      "EDM Services",
      "Prototype Manufacturing",
      "3D Printing Services",
      "Rapid Prototyping",
      "Custom Extrusion",
      "Rubber Molding",
      "Urethane Casting",
      "Metal Spinning",
      "Hydroforming Services",
      "Tube Bending Services"
    ]
  },
  {
    tier: "TIER 10",
    category: "Specialty Home Services",
    description: "Niche markets, loyal customers, minimal competition",
    acquisitionScore: 8,
    businesses: [
      "Pool Service & Repair",
      "Hot Tub Service & Repair",
      "Pool Construction",
      "Pool Resurfacing",
      "Pool Leak Detection",
      "Aquarium Maintenance",
      "Pond & Water Feature Service",
      "Outdoor Kitchen Installation",
      "Outdoor Fireplace/Fire Pit",
      "Landscape Lighting",
      "Holiday Lighting Installation",
      "Awning Installation",
      "Storm Shutter Installation",
      "Home Automation Services",
      "Audio/Visual Installation",
      "Structured Wiring Services",
      "Lightning Protection Systems",
      "Whole House Fan Installation",
      "Attic Fan Installation",
      "Radiant Floor Heating",
      "In-Floor Heating Systems",
      "Geothermal Installation",
      "Ice Melt Systems",
      "Home Elevator Installation",
      "Stair Lift Installation",
      "Dumbwaiter Installation",
      "Safe Installation & Service",
      "Mirror Installation",
      "Shower Door Installation",
      "Blind & Shade Installation",
      "Wallpaper Installation",
      "Popcorn Ceiling Removal",
      "Lead Paint Removal",
      "Asbestos Abatement",
      "Home Staging Services",
      "Move Management Services",
      "Professional Organizing",
      "Estate Sale Services",
      "Auction Services",
      "Piano Moving & Tuning",
      "Grandfather Clock Repair",
      "Antique Restoration",
      "Art Installation Services",
      "Wine Storage Solutions",
      "Gun Safe Installation",
      "Panic Room Construction"
    ]
  },
  {
    tier: "TIER 11",
    category: "Personal & Pet Services",
    description: "Growing demand, recurring revenue",
    acquisitionScore: 7,
    businesses: [
      "Dog Walking Services",
      "Pet Sitting Services",
      "Mobile Pet Grooming",
      "Pet Waste Removal",
      "Dog Training Services",
      "Pet Photography",
      "Pet Transportation",
      "Doggy Daycare",
      "Pet Boarding Facilities",
      "House Sitting Services",
      "Senior Care Services",
      "Home Companion Services",
      "Errand Running Services",
      "Personal Shopping Services",
      "Meal Prep Services",
      "Personal Chef Services",
      "Mobile Hair Salon",
      "Mobile Nail Services",
      "Mobile Massage Therapy",
      "Mobile Spray Tanning",
      "Personal Training (In-Home)",
      "Yoga Instruction (Private)",
      "Music Lessons (In-Home)",
      "Tutoring Services",
      "College Prep Services",
      "Test Prep Services",
      "Driving Schools",
      "CPR Training Services",
      "Notary Services",
      "Mobile Notary Services",
      "Wedding Planning",
      "Event Planning Services",
      "Party Rental Services",
      "Photo Booth Rental",
      "DJ Services",
      "Photography Services",
      "Videography Services",
      "Drone Services"
    ]
  },
  {
    tier: "TIER 12",
    category: "Food & Hospitality",
    description: "Established operations, loyal customers",
    acquisitionScore: 6,
    businesses: [
      "Established Restaurants",
      "Catering Services",
      "Food Trucks/Mobile Food",
      "Bakeries",
      "Coffee Shops (established)",
      "Small Motels/Inns",
      "Event Venues",
      "Banquet Halls",
      "Food Distribution",
      "Wholesale Food Supply",
      "Ice Cream Shops",
      "Donut Shops",
      "Pizza Shops",
      "Deli/Sandwich Shops"
    ]
  },
  {
    tier: "TIER 13",
    category: "Seasonal & Specialty Outdoor",
    description: "Weather-dependent, strong seasonal cash flow",
    acquisitionScore: 7,
    businesses: [
      "Christmas Light Installation",
      "Snow Plowing Services",
      "Ice Control/Salting",
      "Leaf Removal Services",
      "Gutter Guard Installation",
      "Mosquito Misting Systems",
      "Outdoor Pest Barriers",
      "Lawn Aeration Services",
      "Lawn Fertilization",
      "Weed Control Services",
      "Sod Installation",
      "Hydroseeding Services",
      "Artificial Turf Installation",
      "Sports Court Installation",
      "Playground Installation",
      "Batting Cage Installation",
      "Golf Green Installation",
      "Bocce Court Installation",
      "Horseshoe Pit Construction",
      "Zip Line Installation",
      "Treehouse Builders",
      "Greenhouse Installation",
      "Shed Builders",
      "Gazebo Builders",
      "Arbor & Trellis Installation",
      "Retaining Wall Construction",
      "French Drain Installation",
      "Dry Creek Bed Installation",
      "Rain Garden Installation",
      "Bioswale Construction",
      "Erosion Control Services",
      "Land Clearing Services",
      "Stump Grinding Services",
      "Tree Planting Services",
      "Arborist Services",
      "Christmas Tree Farms",
      "Firewood Delivery",
      "Mulch Delivery Services",
      "Topsoil & Gravel Delivery",
      "Boulder & Rock Placement"
    ]
  },
  {
    tier: "TIER 14",
    category: "Specialized Cleaning & Restoration",
    description: "High-margin specialty services",
    acquisitionScore: 8,
    businesses: [
      "Oriental Rug Cleaning",
      "Leather Cleaning & Repair",
      "Chandelier Cleaning",
      "Solar Panel Cleaning",
      "Dryer Vent Cleaning",
      "Kitchen Hood Cleaning",
      "Blind Cleaning Services",
      "Mattress Cleaning",
      "Tile & Grout Cleaning",
      "Stone Restoration",
      "Marble Polishing",
      "Terrazzo Restoration",
      "Wood Floor Restoration",
      "Furniture Restoration",
      "Antique Refinishing",
      "Fire Damage Restoration",
      "Smoke Damage Cleanup",
      "Water Damage Restoration",
      "Storm Damage Cleanup",
      "Trauma Scene Cleanup",
      "Odor Removal Services",
      "Meth Lab Cleanup",
      "Grow House Remediation",
      "Foreclosure Cleanup",
      "Estate Cleanout Services",
      "Junk Removal Services",
      "Appliance Removal",
      "Hot Tub Removal",
      "Piano Removal",
      "Construction Debris Removal",
      "Yard Waste Removal",
      "Scrap Metal Removal",
      "E-Waste Recycling",
      "Document Destruction",
      "Hard Drive Destruction",
      "Medical Waste Disposal",
      "Sharps Disposal Services"
    ]
  },
  {
    tier: "TIER 15",
    category: "Specialty Installation & Repair",
    description: "Technical expertise, limited competition",
    acquisitionScore: 8,
    businesses: [
      "Mailbox Installation",
      "Address Plaque Installation",
      "Flag Pole Installation",
      "Basketball Hoop Installation",
      "Trampoline Assembly",
      "Swing Set Assembly",
      "Exercise Equipment Assembly",
      "Furniture Assembly Services",
      "IKEA Assembly Services",
      "TV Mounting Services",
      "Picture Hanging Services",
      "Shelf Installation",
      "Cabinet Hardware Installation",
      "Grab Bar Installation",
      "Handrail Installation",
      "Baby Proofing Services",
      "Pet Door Installation",
      "Cat Enclosure Installation",
      "Invisible Fence Installation",
      "Electric Gate Repair",
      "Intercom System Repair",
      "Doorbell Installation",
      "Smart Home Installation",
      "WiFi Network Installation",
      "Ethernet Cabling",
      "Coax Cable Installation",
      "Satellite Dish Installation",
      "Antenna Installation",
      "Weather Station Installation",
      "Flag & Banner Installation",
      "Neon Sign Repair",
      "LED Sign Installation",
      "Monument Sign Installation",
      "Vehicle Wrap Installation",
      "Boat Wrap Services",
      "RV Detailing Services",
      "Aircraft Detailing",
      "Ceramic Coating Services",
      "Paint Protection Film",
      "Headlight Restoration"
    ]
  },
  {
    tier: "TIER 16",
    category: "Distribution & Wholesale",
    description: "Baby boomer-dominated supply chain businesses",
    acquisitionScore: 8,
    businesses: [
      "Building Materials Distribution",
      "Plumbing Supply Distribution",
      "Electrical Supply Wholesale",
      "HVAC Parts Distribution",
      "Industrial Supply Distribution",
      "Safety Equipment Distribution",
      "Janitorial Supply Distribution",
      "Chemical Distribution",
      "Paint & Coating Distribution",
      "Hardware Store (Independent)",
      "Lumber Yard",
      "Fastener & Tool Distribution",
      "Packaging Supply Distribution",
      "Paper Products Distribution",
      "Food Service Equipment Distribution",
      "Medical Supply Distribution",
      "Dental Supply Distribution",
      "Veterinary Supply Distribution",
      "Beauty Supply Distribution",
      "Auto Parts Distribution",
      "Marine Parts Distribution",
      "RV Parts & Accessories",
      "Motorcycle Parts Distribution",
      "Welding Supply Distribution",
      "Abrasives Distribution",
      "Bearing & Power Transmission",
      "Hydraulic & Pneumatic Supply",
      "Material Handling Equipment",
      "Office Supply Distribution",
      "Restaurant Supply Distribution",
      "Bakery Supply Distribution",
      "Florist Supply Distribution",
      "Pool & Spa Supply Distribution",
      "Sporting Goods Distribution",
      "Toy & Hobby Distribution"
    ]
  },
  {
    tier: "TIER 17",
    category: "Transportation & Logistics",
    description: "Owner-operator dominated sectors",
    acquisitionScore: 7,
    businesses: [
      "Trucking Companies (Local)",
      "Freight Brokerage",
      "Courier Services",
      "Medical Transport (Non-Emergency)",
      "School Bus Services",
      "Charter Bus Services",
      "Limousine Services",
      "Taxi Services",
      "Moving & Storage",
      "Specialized Transport (Oversized)",
      "Auto Transport Services",
      "Boat Transport Services",
      "Hot Shot Trucking",
      "Refrigerated Transport",
      "Hazmat Transport",
      "Dump Truck Services",
      "Concrete Delivery",
      "Crane Services",
      "Rigging Services",
      "Expedited Freight",
      "Last Mile Delivery",
      "White Glove Delivery",
      "Furniture Delivery",
      "Appliance Delivery",
      "Medical Equipment Delivery",
      "Construction Material Delivery",
      "Propane Delivery",
      "Heating Oil Delivery",
      "Water Delivery Services",
      "Ice Delivery Services",
      "Vending Route Services",
      "Newspaper Delivery Routes",
      "Airport Shuttle Services",
      "Wine & Beverage Distribution",
      "Intermodal Transportation"
    ]
  },
  {
    tier: "TIER 18",
    category: "Specialized Manufacturing",
    description: "Small-scale production with skilled workforce",
    acquisitionScore: 7,
    businesses: [
      "Cabinet Making",
      "Custom Millwork",
      "Sign Manufacturing",
      "Trophy & Award Manufacturing",
      "Textile Manufacturing",
      "Uniform Manufacturing",
      "Embroidery Services",
      "Screen Printing",
      "Custom Packaging",
      "Label Printing",
      "Business Forms Printing",
      "Promotional Products",
      "Custom Metalwork",
      "Ornamental Iron Work",
      "Custom Glass Fabrication",
      "Stone Cutting & Fabrication",
      "Precast Concrete Manufacturing",
      "Pallet Manufacturing",
      "Crate & Container Manufacturing",
      "Mattress Manufacturing",
      "Custom Furniture Manufacturing",
      "Upholstery Services",
      "Canvas Products Manufacturing",
      "Awning Manufacturing",
      "Flag & Banner Manufacturing",
      "Foam Fabrication",
      "Rubber Stamp Manufacturing",
      "Name Badge Manufacturing",
      "Plastic Fabrication",
      "Acrylic Fabrication",
      "Custom Gasket Manufacturing",
      "Spring Manufacturing",
      "Wire Products Manufacturing",
      "Brush Manufacturing",
      "Mop & Broom Manufacturing",
      "Candle Manufacturing",
      "Soap Manufacturing",
      "Custom Chemical Blending",
      "Pet Food Manufacturing",
      "Specialty Food Production"
    ]
  },
  {
    tier: "TIER 19",
    category: "Marine & Recreational Services",
    description: "Lifestyle businesses in coastal/lake regions",
    acquisitionScore: 6,
    businesses: [
      "Marina Services",
      "Boat Storage Facilities",
      "Yacht Maintenance",
      "Marine Canvas & Upholstery",
      "Boat Detailing Services",
      "Marine Electronics Installation",
      "Boat Bottom Painting",
      "Dive Shop Services",
      "Fishing Charter Services",
      "Boat Rental Services",
      "Jet Ski Rental",
      "Kayak/Canoe Rental",
      "Bait & Tackle Shops",
      "Marine Fuel Services",
      "Boat Launching Services",
      "Dock Building & Repair",
      "Seawall Construction",
      "Marine Salvage Services",
      "Boat Winterization Services",
      "Sailing School",
      "Wakeboard/Ski School",
      "Parasailing Services",
      "Whale Watching Tours",
      "Sunset Cruise Services",
      "Party Boat Services",
      "Water Taxi Services",
      "Ferry Services",
      "Houseboat Rental",
      "Pontoon Boat Rental",
      "Marine Surveying",
      "Boat Brokerage",
      "Yacht Management",
      "Ship Chandlery",
      "Marine Insurance Services",
      "Boat Financing Services",
      "Marina Restaurant",
      "Dockside Store",
      "Marine Towing Services",
      "Underwater Services",
      "Commercial Diving Services"
    ]
  },
  {
    tier: "TIER 20",
    category: "Agricultural & Rural Services",
    description: "Rural America backbone businesses",
    acquisitionScore: 7,
    businesses: [
      "Farm Equipment Repair",
      "Grain Elevator Services",
      "Custom Harvesting",
      "Livestock Transportation",
      "Feed Store Operations",
      "Farm Supply Stores",
      "Fence Installation (Agricultural)",
      "Barn Builders",
      "Silo Services",
      "Irrigation Installation (Agricultural)",
      "Soil Testing Services",
      "Crop Spraying Services",
      "Seed Cleaning Services",
      "Custom Hay Baling",
      "Horse Boarding Facilities",
      "Riding Lesson Services",
      "Farrier Services",
      "Large Animal Veterinary",
      "Livestock Auction Services",
      "Agricultural Tire Services",
      "Grain Drying Services",
      "Custom Fertilizer Application",
      "Manure Management Services",
      "Agricultural Drainage",
      "Land Leveling Services",
      "Orchard Management",
      "Vineyard Management",
      "Greenhouse Operations",
      "Nursery Operations",
      "Sod Farm Operations",
      "Christmas Tree Farm",
      "Pumpkin Patch/Corn Maze",
      "U-Pick Operations",
      "Farm Equipment Rental",
      "Agricultural Consulting",
      "Crop Insurance Services",
      "Rural Internet Services",
      "Rural Propane Services",
      "Well Water Services",
      "Rural Waste Management"
    ]
  }
];

// Get all business types as a flat array
export const ALL_BUSINESS_TYPES: string[] = GREY_TSUNAMI_CATEGORIES.reduce(
  (acc, category) => [...acc, ...category.businesses],
  [] as string[]
);

// Search function for businesses
export function searchBusinessTypes(query: string): string[] {
  const searchLower = query.toLowerCase().trim();
  
  return ALL_BUSINESS_TYPES.filter(business =>
    business.toLowerCase().includes(searchLower)
  ).sort((a, b) => {
    // Prioritize exact matches
    const aLower = a.toLowerCase();
    const bLower = b.toLowerCase();
    
    if (aLower === searchLower) return -1;
    if (bLower === searchLower) return 1;
    
    // Then prioritize starts with
    if (aLower.startsWith(searchLower) && !bLower.startsWith(searchLower)) return -1;
    if (!aLower.startsWith(searchLower) && bLower.startsWith(searchLower)) return 1;
    
    return a.localeCompare(b);
  });
}

// Get businesses by category
export function getBusinessesByCategory(categoryName: string): string[] {
  const category = GREY_TSUNAMI_CATEGORIES.find(
    cat => cat.category.toLowerCase() === categoryName.toLowerCase()
  );
  return category ? category.businesses : [];
}

// Get category for a business type
export function getCategoryForBusiness(businessType: string): BusinessCategory | undefined {
  return GREY_TSUNAMI_CATEGORIES.find(category =>
    category.businesses.some(
      business => business.toLowerCase() === businessType.toLowerCase()
    )
  );
}

// Generate acquisition-focused keywords for FB Ad Library
export function generateAcquisitionKeywords(businessType: string, city: string): string[] {
  const keywords: string[] = [];
  const years = ['1990', '1995', '2000', '2005', '2010'];
  
  // Basic patterns
  keywords.push(
    `${businessType} ${city}`,
    `${city} ${businessType}`,
    `${businessType} near me`,
    `local ${businessType}`,
    `${businessType} services ${city}`
  );
  
  // Family/established business patterns
  keywords.push(
    `family owned ${businessType}`,
    `established ${businessType} ${city}`,
    `${businessType} since ${years[Math.floor(Math.random() * years.length)]}`,
    `trusted ${businessType} ${city}`,
    `experienced ${businessType}`
  );
  
  // Anniversary/longevity patterns
  keywords.push(
    `${businessType} 25 years`,
    `${businessType} 30 years experience`,
    `${businessType} serving ${city}`,
    `${businessType} locally owned`,
    `${businessType} family business`
  );
  
  // Traditional business indicators
  keywords.push(
    `${businessType} company ${city}`,
    `${businessType} contractor ${city}`,
    `professional ${businessType}`,
    `licensed ${businessType}`,
    `certified ${businessType}`
  );
  
  return keywords;
}

// Score a business for acquisition potential
export function calculateAcquisitionScore(
  businessType: string,
  yearsInBusiness?: number,
  hasWebsite?: boolean,
  runningAds?: boolean
): number {
  let score = 0;
  
  // Get base score from category
  const category = getCategoryForBusiness(businessType);
  if (category) {
    score = category.acquisitionScore;
  }
  
  // Adjust based on years in business
  if (yearsInBusiness) {
    if (yearsInBusiness >= 20) score += 2;
    else if (yearsInBusiness >= 15) score += 1.5;
    else if (yearsInBusiness >= 10) score += 1;
  }
  
  // Adjust based on digital presence
  if (!hasWebsite) score += 0.5; // Less tech-savvy = better opportunity
  if (runningAds) score += 0.5; // Shows business activity
  
  return Math.min(10, score); // Cap at 10
}